// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.2
// source: kademlia.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PING struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId []byte `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
}

func (x *PING) Reset() {
	*x = PING{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kademlia_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PING) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PING) ProtoMessage() {}

func (x *PING) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PING.ProtoReflect.Descriptor instead.
func (*PING) Descriptor() ([]byte, []int) {
	return file_kademlia_proto_rawDescGZIP(), []int{0}
}

func (x *PING) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

type PONG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId []byte `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
}

func (x *PONG) Reset() {
	*x = PONG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kademlia_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PONG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PONG) ProtoMessage() {}

func (x *PONG) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PONG.ProtoReflect.Descriptor instead.
func (*PONG) Descriptor() ([]byte, []int) {
	return file_kademlia_proto_rawDescGZIP(), []int{1}
}

func (x *PONG) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

type FIND_NODE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId []byte `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
}

func (x *FIND_NODE) Reset() {
	*x = FIND_NODE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kademlia_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FIND_NODE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FIND_NODE) ProtoMessage() {}

func (x *FIND_NODE) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FIND_NODE.ProtoReflect.Descriptor instead.
func (*FIND_NODE) Descriptor() ([]byte, []int) {
	return file_kademlia_proto_rawDescGZIP(), []int{2}
}

func (x *FIND_NODE) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

type NODE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Port    int32  `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	NodeId  []byte `protobuf:"bytes,3,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
}

func (x *NODE) Reset() {
	*x = NODE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kademlia_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NODE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NODE) ProtoMessage() {}

func (x *NODE) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NODE.ProtoReflect.Descriptor instead.
func (*NODE) Descriptor() ([]byte, []int) {
	return file_kademlia_proto_rawDescGZIP(), []int{3}
}

func (x *NODE) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NODE) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NODE) GetNodeId() []byte {
	if x != nil {
		return x.NodeId
	}
	return nil
}

var File_kademlia_proto protoreflect.FileDescriptor

var file_kademlia_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47, 0x12,
	0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x1e, 0x0a, 0x04, 0x50, 0x4f, 0x4e, 0x47, 0x12,
	0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x09, 0x46, 0x49, 0x4e, 0x44, 0x5f,
	0x4e, 0x4f, 0x44, 0x45, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x04,
	0x4e, 0x4f, 0x44, 0x45, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f,
	0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kademlia_proto_rawDescOnce sync.Once
	file_kademlia_proto_rawDescData = file_kademlia_proto_rawDesc
)

func file_kademlia_proto_rawDescGZIP() []byte {
	file_kademlia_proto_rawDescOnce.Do(func() {
		file_kademlia_proto_rawDescData = protoimpl.X.CompressGZIP(file_kademlia_proto_rawDescData)
	})
	return file_kademlia_proto_rawDescData
}

var file_kademlia_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kademlia_proto_goTypes = []any{
	(*PING)(nil),      // 0: proto.PING
	(*PONG)(nil),      // 1: proto.PONG
	(*FIND_NODE)(nil), // 2: proto.FIND_NODE
	(*NODE)(nil),      // 3: proto.NODE
}
var file_kademlia_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kademlia_proto_init() }
func file_kademlia_proto_init() {
	if File_kademlia_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kademlia_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PING); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kademlia_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PONG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kademlia_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FIND_NODE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kademlia_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*NODE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kademlia_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kademlia_proto_goTypes,
		DependencyIndexes: file_kademlia_proto_depIdxs,
		MessageInfos:      file_kademlia_proto_msgTypes,
	}.Build()
	File_kademlia_proto = out.File
	file_kademlia_proto_rawDesc = nil
	file_kademlia_proto_goTypes = nil
	file_kademlia_proto_depIdxs = nil
}
